apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-consumer-service
spec:
  type: {{ .Values.services.consumer.type }}
  selector:
    name: {{ .Release.Name }}-consumer
  ports:
  {{- toYaml .Values.services.consumer.ports | nindent 2 }}