apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-producer-service
spec:
  type: {{ .Values.services.producer.type }}
  selector:
    name: {{ .Release.Name }}-producer
  ports:
  {{- toYaml .Values.services.producer.ports | nindent 2 }}